# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-06 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toilet_questionnaire_3_group', to='otree.Session')),
            ],
            options={
                'db_table': 'toilet_questionnaire_3_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('q3_second_game_results_surprised', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_second_game_results_satisfied', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_second_game_results_upset', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_second_game_teamwork', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_second_game_teamspirit', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_communication_inputs_maxresources_how_useful', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_followed_communication_inputs', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_took_advantage_communication_inputs', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_majority_followed_communication_inputs', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_majority_took_advantage_communication_inputs', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_minority_followed_communication_inputs', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_minority_took_advantage_communication_inputs', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_how_max_resources_communication_inputs_if_followed', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_after_second_round_like_others', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_second_round_impressions', otree.db.models.LongStringField(null=True)),
                ('q3_best_strategy_to_max_resources', otree.db.models.LongStringField(null=True)),
                ('q3_gender', otree.db.models.StringField(choices=[('M', 'M'), ('F', 'F')], max_length=10000, null=True)),
                ('q3_birthday', otree.db.models.LongStringField(null=True)),
                ('q3_main_subject_in_university', otree.db.models.LongStringField(null=True)),
                ('q3_already_take_part_in_a_problem_solving', otree.db.models.StringField(choices=[('Ja', 'Ja'), ('Nein', 'Nein')], max_length=255, null=True)),
                ('q3_already_took_part_x_times_for_x_months', otree.db.models.LongStringField(default='X Male und das letzte Mal vor X Monaten.', null=True)),
                ('q3_experiment_itself_was_interessting', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_were_you_personally_engaged_achieving_good_results', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_dificult_understanding_and_solving_the_problem', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_was_it_obvious_what_to_do', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_count_unclear_questions', otree.db.models.LongStringField(null=True)),
                ('q3_unclear_questions_description', otree.db.models.LongStringField(null=True)),
                ('q3_technical_issues', otree.db.models.StringField(choices=[('Ja', 'Ja'), ('Nein', 'Nein')], max_length=255, null=True)),
                ('q3_technical_issues_details', otree.db.models.LongStringField(null=True)),
                ('q3_opinion_about_questions_and_hypotheses', otree.db.models.LongStringField(null=True)),
                ('q3_confidant_second_game_teamwork', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_confidant_second_game_teamspirit', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_confidant_majority_followed_communication_inputs', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_confidant_majority_took_advantage_communication_inputs', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_confidant_minority_followed_communication_inputs', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_confidant_minority_took_advantage_communication_inputs', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_confidant_best_strategy_to_max_resources', otree.db.models.LongStringField(null=True)),
                ('q3_confidant_gender', otree.db.models.StringField(choices=[('M', 'M'), ('F', 'F')], max_length=10000, null=True)),
                ('q3_confidant_birthday', otree.db.models.LongStringField(null=True)),
                ('q3_confidant_main_subject_in_university', otree.db.models.LongStringField(null=True)),
                ('q3_confidant_already_take_part_in_a_problem_solving', otree.db.models.StringField(choices=[('Ja', 'Ja'), ('Nein', 'Nein')], max_length=255, null=True)),
                ('q3_confidant_already_took_part_x_times_for_x_months', otree.db.models.LongStringField(default='X Male und das letzte Mal vor X Monaten.', null=True)),
                ('q3_confidant_experiment_itself_was_interessting', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_confidant_were_you_personally_engaged_achieving_good_results', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_confidant_dificult_understanding_and_solving_the_problem', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_confidant_was_it_obvious_what_to_do', otree.db.models.PositiveIntegerField(null=True)),
                ('q3_confidant_count_unclear_questions', otree.db.models.LongStringField(null=True)),
                ('q3_confidant_unclear_questions_description', otree.db.models.LongStringField(null=True)),
                ('q3_confidant_technical_issues', otree.db.models.StringField(choices=[('Ja', 'Ja'), ('Nein', 'Nein')], max_length=255, null=True)),
                ('q3_confidant_technical_issues_details', otree.db.models.LongStringField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toilet_questionnaire_3.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toilet_questionnaire_3_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toilet_questionnaire_3_player', to='otree.Session')),
            ],
            options={
                'db_table': 'toilet_questionnaire_3_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toilet_questionnaire_3_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'toilet_questionnaire_3_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toilet_questionnaire_3.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toilet_questionnaire_3.Subsession'),
        ),
    ]
