# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-06 14:16
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet_questionnaire_3', '0003_auto_20180306_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='q3_birthday',
            field=otree.db.models.StringField(default='XXXX', editable=False, max_length=4, null=True),
        ),
    ]
