# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-06 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toilet_questionnaire_1_group', to='otree.Session')),
            ],
            options={
                'db_table': 'toilet_questionnaire_1_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('q1_first_game_judge_surprised', otree.db.models.PositiveIntegerField(null=True)),
                ('q1_first_game_judge_satisfied', otree.db.models.PositiveIntegerField(null=True)),
                ('q1_first_game_judge_upset', otree.db.models.PositiveIntegerField(null=True)),
                ('q1_players_helping_each_other', otree.db.models.PositiveIntegerField(null=True)),
                ('q1_team_spirit_or_cohesion', otree.db.models.PositiveIntegerField(null=True)),
                ('q1_important_presented_image_of_and_to_yourself', otree.db.models.PositiveIntegerField(null=True)),
                ('q1_important_maximum_and_fair_resources_to_everyone', otree.db.models.PositiveIntegerField(null=True)),
                ('q1_important_other_members_trust_in_you', otree.db.models.PositiveIntegerField(null=True)),
                ('q1_important_not_you_maximum_and_fair_resources_to_everyone', otree.db.models.PositiveIntegerField(null=True)),
                ('q1_trust_do_you_have_into_other_members', otree.db.models.PositiveIntegerField(null=True)),
                ('q1_how_much_do_you_like_the_other_team_members', otree.db.models.PositiveIntegerField(null=True)),
                ('q1_how_good_do_you_understand_solving', otree.db.models.PositiveIntegerField(null=True)),
                ('q1_how_good_do_the_other_group_members_understand_solving', otree.db.models.PositiveIntegerField(null=True)),
                ('q1_how_to_improve_the_groups_behavior_to_maximize_resources', otree.db.models.LongStringField(null=True)),
                ('q1_if_communicate_what_would_you_say_and_why', otree.db.models.LongStringField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toilet_questionnaire_1.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toilet_questionnaire_1_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toilet_questionnaire_1_player', to='otree.Session')),
            ],
            options={
                'db_table': 'toilet_questionnaire_1_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toilet_questionnaire_1_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'toilet_questionnaire_1_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toilet_questionnaire_1.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toilet_questionnaire_1.Subsession'),
        ),
    ]
