# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-06 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toilet_questionnaire_2_group', to='otree.Session')),
            ],
            options={
                'db_table': 'toilet_questionnaire_2_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('q2_communication_surprised', otree.db.models.PositiveIntegerField(null=True)),
                ('q2_communication_satisfied', otree.db.models.PositiveIntegerField(null=True)),
                ('q2_communication_upset', otree.db.models.PositiveIntegerField(null=True)),
                ('q2_fair_discussion', otree.db.models.PositiveIntegerField(null=True)),
                ('q2_fear_criticism', otree.db.models.PositiveIntegerField(null=True)),
                ('q2_communication_to_be_right', otree.db.models.PositiveIntegerField(null=True)),
                ('q2_give_opinion', otree.db.models.PositiveIntegerField(null=True)),
                ('q2_others_opinions', otree.db.models.PositiveIntegerField(null=True)),
                ('q2_communication_whine', otree.db.models.PositiveIntegerField(null=True)),
                ('q2_inputs_considered', otree.db.models.PositiveIntegerField(null=True)),
                ('q2_best_player', otree.db.models.StringField(max_length=255, null=True)),
                ('q2_communication_focused', otree.db.models.PositiveIntegerField(null=True)),
                ('q2_communication_efficient', otree.db.models.PositiveIntegerField(null=True)),
                ('q2_communication_interested_in_solution', otree.db.models.PositiveIntegerField(null=True)),
                ('q2_discussion_tense', otree.db.models.PositiveIntegerField(null=True)),
                ('q2_discussion_tense_why', otree.db.models.LongStringField(null=True)),
                ('q2_chat_instructions_helpful', otree.db.models.PositiveIntegerField(null=True)),
                ('q2_chat_instructions_followed', otree.db.models.PositiveIntegerField(null=True)),
                ('q2_was_there_negative_participant', otree.db.models.StringField(choices=[('Ja', 'Ja'), ('Nein', 'Nein')], max_length=255, null=True)),
                ('q2_negative_participant', otree.db.models.LongStringField(default='Fügen Sie hier die Spielernamen hinzu.', null=True)),
                ('q2_was_there_positive_participant', otree.db.models.StringField(choices=[('Ja', 'Ja'), ('Nein', 'Nein')], max_length=255, null=True)),
                ('q2_positive_participant', otree.db.models.LongStringField(default='Fügen Sie hier die Spielernamen hinzu.', null=True)),
                ('q2_confidant_followed_chat_intstructions', otree.db.models.PositiveIntegerField(null=True)),
                ('q2_confidant_difficulty_chat_instructions', otree.db.models.PositiveIntegerField(null=True)),
                ('q2_confidant_problems_chat_instructions', otree.db.models.LongStringField(null=True)),
                ('q2_confidant_others_found_out_confidant', otree.db.models.PositiveIntegerField(null=True)),
                ('q2_confidant_others_found_out_confidant_why', otree.db.models.LongStringField(null=True)),
                ('q2_confidant_pleased_about_being_chosen', otree.db.models.PositiveIntegerField(null=True)),
                ('q2_confidant_would_have_participated_if_knew', otree.db.models.PositiveIntegerField(null=True)),
                ('q2_confidant_comments_in_general', otree.db.models.LongStringField(null=True)),
                ('q2_confidant_influence_inputs', otree.db.models.PositiveIntegerField(null=True)),
                ('q2_confidant_inputs_being_ignored_others', otree.db.models.PositiveIntegerField(null=True)),
                ('q2_confidant_cleaning_how_to_proceed', otree.db.models.StringField(choices=[('Die Gruppe einigte sich auf klare Regeln, wie sich jeder im Spiel verhalten soll.', 'Die Gruppe einigte sich auf klare Regeln, wie sich jeder im Spiel verhalten soll.'), ('Es wurde vage vereinbart, wie sich jeder im Spiel verhalten soll.', 'Es wurde vage vereinbart, wie sich jeder im Spiel verhalten soll.'), ('Verschiedene Möglichkeiten, wie sich jeder im Spiel verhalten soll, wurden angesprochen, aber es kam nie zu einer Einigung auf eine der Möglichkeiten.', 'Verschiedene Möglichkeiten, wie sich jeder im Spiel verhalten soll, wurden angesprochen, aber es kam nie zu einer Einigung auf eine der Möglichkeiten.'), ('Obschon keine konkreten Möglichkeiten genannt wurden, wie sich jeder im Spiel verhalten soll wurde mir klarer, wie ich meine Entscheidungen verbessern könnte.', 'Obschon keine konkreten Möglichkeiten genannt wurden, wie sich jeder im Spiel verhalten soll wurde mir klarer, wie ich meine Entscheidungen verbessern könnte.'), ('Es wurde zwar über das Reinigen bzw. Verhalten im Spiel geredet, dies hatte aber keinen Bezug darauf, wie man in weiteren Spielen handeln soll.', 'Es wurde zwar über das Reinigen bzw. Verhalten im Spiel geredet, dies hatte aber keinen Bezug darauf, wie man in weiteren Spielen handeln soll.'), ("Das Thema 'Toilettenreinigung' bzw. Verhalten im Spiel wurde gar nicht angesprochen", "Das Thema 'Toilettenreinigung' bzw. Verhalten im Spiel wurde gar nicht angesprochen")], max_length=255, null=True)),
                ('q2_confidant_how_to_realize_recommendations', otree.db.models.LongStringField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toilet_questionnaire_2.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toilet_questionnaire_2_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toilet_questionnaire_2_player', to='otree.Session')),
            ],
            options={
                'db_table': 'toilet_questionnaire_2_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toilet_questionnaire_2_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'toilet_questionnaire_2_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toilet_questionnaire_2.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toilet_questionnaire_2.Subsession'),
        ),
    ]
