# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-06 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debriefing_group', to='otree.Session')),
            ],
            options={
                'db_table': 'debriefing_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('debriefing_guess_which_group', otree.db.models.StringField(choices=[('Gruppe mit Anweisungen für alle zu positiver Kommunikation', 'Gruppe mit Anweisungen für alle zu positiver Kommunikation'), ('Gruppe mit Konfident mit positiver Kommunikation', 'Gruppe mit Konfident mit positiver Kommunikation'), ('Gruppe mit Konfident mit negativer Kommunikation', 'Gruppe mit Konfident mit negativer Kommunikation'), ('Kontrollgruppe ohne eigentliche Anweisungen', 'Kontrollgruppe ohne eigentliche Anweisungen'), ('Weiss nicht', 'Weiss nicht')], max_length=255, null=True)),
                ('debriefing_sure_about_confidant_in_group', otree.db.models.PositiveIntegerField(null=True)),
                ('debriefing_who_was_confidant', otree.db.models.StringField(max_length=255, null=True)),
                ('what_made_you_assume_confidant', otree.db.models.LongStringField(default='n/a', null=True)),
                ('debriefing_feedback', otree.db.models.LongStringField(null=True)),
                ('confidant_debriefing_feedback', otree.db.models.LongStringField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='debriefing.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debriefing_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debriefing_player', to='otree.Session')),
            ],
            options={
                'db_table': 'debriefing_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debriefing_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'debriefing_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debriefing.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debriefing.Subsession'),
        ),
    ]
